spring:
  application:
    name: Bong Rumluos
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
#  profiles:
#    active: dev
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:file:D:/others/Learing/h2/rumluos/rumluos;DB_CLOSE_DELAY=-1;
    username: lang
    password: lang123
    driver-class-name: org.h2.Driver
  jpa:
    #    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
server:
  port: 9090

