spring:
  spring:
    jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false
  application:
    name: Bong Rumluos
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:file:D:/others/Learing/h2/rumluos/rumluos;DB_CLOSE_DELAY=-1;
    username: lang
    password: lang123
    driver-class-name: org.h2.Driver
  jpa:
    #    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        #        generate_statistics: true
        enable_lazy_load_no_trans: true
        show: true
        format_sql: true
        #        use_sql_comments: true
        jdbc:
          fetch_size: 5
          batch_size: 50
          passDistinctThrough: false
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
server:
  port: 9090
logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG
        messaging: DEBUG
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          description:
#            sql:
#              BasicBinder: TRACE